# @package _global_

eval_timestamp: ${now:%Y%m%d_%H%M%S}
eval_name: TEST
eval_log_dir: logs_eval/${eval_name}/${eval_timestamp}
hydra:
  run:
    dir: ${eval_log_dir}

#robot:
#  randomize_link_body_names : [
#      'pelvis', 'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link',
#      'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link',
#  ]
