# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 20
  dof_obs_size: 19
  actions_dim: 19
  lower_body_actions_dim: 10 # Yuanhang
  upper_body_actions_dim: 9 # Yuanhang
  policy_obs_dim: -1 # Jiawei
  critic_obs_dim: -1
  # policy_obs_dim: 45 # Jiawei
  # critic_obs_dim: 238
  # policy_obs_dim: 45 # Jiawei
  # policy_obs_dim: 241 # Jiawei
  # self_obs_max_coords: 298  # ${eval:1+20*(3+6+3+3)-3}

  # h1的ankle时pitch
  key_bodies: ["left_ankle_link", "right_ankle_link"]
  contact_bodies: [ "left_ankle_link", "right_ankle_link" ]
  num_feet: 2
  right_foot_name: "right_ankle_link"
  left_foot_name: "left_ankle_link"
  foot_name: "ankle_link"
  knee_name: "knee_link"
  has_torso: True
  torso_name: "torso_link"
  has_upper_body_dof: True
  dof_names: ['left_hip_yaw_joint', 'left_hip_roll_joint', 'left_hip_pitch_joint', 'left_knee_joint', 'left_ankle_joint',
              'right_hip_yaw_joint', 'right_hip_roll_joint', 'right_hip_pitch_joint', 'right_knee_joint', 'right_ankle_joint',
              'torso_joint',
              'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint','left_elbow_joint',
              'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint']

  upper_dof_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint','left_elbow_joint',
                    'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint']

  upper_left_arm_dof_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint','left_elbow_joint']
  upper_right_arm_dof_names: ['right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint']
  lower_dof_names: ['left_hip_yaw_joint', 'left_hip_roll_joint', 'left_hip_pitch_joint', 'left_knee_joint', 'left_ankle_joint',
                    'right_hip_yaw_joint', 'right_hip_roll_joint', 'right_hip_pitch_joint', 'right_knee_joint', 'right_ankle_joint',
                    'torso_joint']
  waist_dof_names: ['torso_joint']
  dof_pos_lower_limit_list: [-0.4300, -0.4300, -3.1400, -0.2600, -0.8700, 
                             -0.4300, -0.4300, -3.1400, -0.2600, -0.8700, 
                             -2.3500,
                             -2.8700, -0.3400, -1.3000, -1.2500,
                             -2.8700, -3.1100, -4.4500, -1.2500]
  dof_pos_upper_limit_list: [0.4300, 0.4300, 2.5300, 2.0500, 0.5200, 
                             0.4300, 0.4300, 2.5300, 2.0500, 0.5200, 
                             2.3500,
                             2.8700, 3.1100, 4.4500, 2.6100,
                             2.8700, 0.3400, 1.3000, 2.6100]
  dof_vel_limit_list: [23.0, 23.0, 23.0, 14.0, 9.0, 
                       23.0, 23.0, 23.0, 14.0, 9.0, 
                       23.0,
                       9.0, 9.0, 20.0, 20.0, 
                       9.0, 9.0, 20.0, 20.0]
  dof_effort_limit_list: [200.0, 200.0, 200.0, 300.0, 40.0, 
                          200.0, 200.0, 200.0, 300.0, 40.0, 
                          200.0,
                          40.0, 40.0, 18.0, 18.0, 
                          40.0, 40.0, 18.0, 18.0]
  
  # only apply for isaacsim
  dof_armature_list: [0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03,
                      0.03, 0.03, 0.03, 0.03,
                      0.04, 0.03, 0.03, 0.03]
  # only apply for isaacsim
  dof_joint_friction_list: [0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03,
                            0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03]

  body_names: ['pelvis',
                'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link', 'left_ankle_link',
                'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_link',
                'torso_link',
                'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
                'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

  terminate_after_contacts_on : ["pelvis", "shoulder", "hip"]
  penalize_contacts_on: ["pelvis", "shoulder", "hip"]
  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_hip_yaw_joint: 0.0
      left_hip_roll_joint: 0.0
      left_hip_pitch_joint: 0.0
      left_knee_joint: 0.0
      left_ankle_joint: 0.0
      right_hip_yaw_joint: 0.0
      right_hip_roll_joint: 0.0
      right_hip_pitch_joint: 0.0
      right_knee_joint: 0.0
      right_ankle_joint: 0.0
      torso_joint: 0.0
      left_shoulder_pitch_joint: 0.
      left_shoulder_roll_joint: 0.
      left_shoulder_yaw_joint: 0.
      left_elbow_joint: 0.
      right_shoulder_pitch_joint: 0.
      right_shoulder_roll_joint: 0.
      right_shoulder_yaw_joint: 0.
      right_elbow_joint: 0.



  # randomize_link_body_names: [
  #   'pelvis', 'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link',
  #   'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link',
  # ]

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_yaw: 100
      hip_roll: 100
      hip_pitch: 100
      knee: 200
      ankle: 20
      torso: 400
      shoulder_pitch: 90
      shoulder_roll: 60
      shoulder_yaw: 20
      elbow: 60


    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_yaw: 2.5
      hip_roll: 2.5
      hip_pitch: 2.5
      knee: 5.0
      ankle: 0.2
      torso: 5.0
      shoulder_pitch: 2.0
      shoulder_roll: 1.0
      shoulder_yaw: 0.4
      elbow: 1.0

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "h1/${robot.asset.robot_type}.urdf"
    usd_file: "h1/${robot.asset.robot_type}.usd"
    xml_file: "h1/${robot.asset.robot_type}.xml"
    # xml_file: "g1/${robot.asset.robot_type}_fitmotionONLY.xml"
    robot_type: h1
    self_collisions: 0 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

    fix_base_link: False # TEST: fix base link to world

  motion:
    motion_lib_type: 'WJX'
    motion_file : ???
    asset:
      assetRoot: "description/robots/h1/"
      assetFileName: "h1.xml"
      urdfFileName: "h1.urdf"

    humanoid_type: h1
    bias_offset: False
    has_self_collision: True
    has_mesh: False
    has_jt_limit: False
    has_dof_subset: True
    has_upright_start: True
    has_smpl_pd_offset: False
    remove_toe: False # For humanoid's geom toe
    motion_sym_loss: False
    sym_loss_coef: 1
    big_ankle: True

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: False

    masterfoot: False
    freeze_toe: false
    freeze_hand: False
    box_body: True
    real_weight: True
    real_weight_porpotion_capsules: True
    real_weight_porpotion_boxes: True

    body_names: ['pelvis',
                'left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link', 'left_ankle_link',
                'right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_link',
                'torso_link',
                'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
                'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

    limb_weight_group: 
      - ['left_hip_yaw_link', 'left_hip_roll_link', 'left_hip_pitch_link', 'left_knee_link', 'left_ankle_link']
      - ['right_hip_yaw_link', 'right_hip_roll_link', 'right_hip_pitch_link', 'right_knee_link', 'right_ankle_link']
      - ['pelvis', 'torso_link']
      - ['left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link']
      - ['right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

    dof_names: ['left_hip_yaw_joint', 'left_hip_roll_joint', 'left_hip_pitch_joint', 'left_knee_joint', 'left_ankle_joint',
              'right_hip_yaw_joint', 'right_hip_roll_joint', 'right_hip_pitch_joint', 'right_knee_joint', 'right_ankle_joint',
              'torso_joint',
              'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint','left_elbow_joint',
              'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint']

    right_foot_name: 'r_foot_roll'
    left_foot_name: 'l_foot_roll'


    nums_extend_bodies: 3
    extend_config:
      - joint_name: "left_hand_link"
        parent_name: "left_elbow_link"
        pos: [0.25, 0.0, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_hand_link"
        parent_name: "right_elbow_link"
        pos: [0.25, 0.0, 0.0]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "head_link"
        parent_name: "torso_link"
        pos: [0.0, 0.0, 0.42]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z


    motion_tracking_link:
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"

    lower_body_link:
      - "pelvis"
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "left_knee_link"
      - "left_ankle_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
      - "right_knee_link"
      - "right_ankle_link"
      - "torso_link"

    upper_body_link:
      - "left_shoulder_pitch_link"
      - "left_shoulder_roll_link"
      - "left_shoulder_yaw_link"
      - "left_elbow_link"
      - "right_shoulder_pitch_link"
      - "right_shoulder_roll_link"
      - "right_shoulder_yaw_link"
      - "right_elbow_link"
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"


    pelvis_link: "pelvis"
    base_link: "torso_link"
    hips_link:
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
    
    joint_matches:
      - ["pelvis", "Pelvis"]
      - ["left_hip_pitch_link", "L_Hip"]
      - ["left_knee_link", "L_Knee"]
      - ["left_ankle_link", "L_Ankle"]
      - ["right_hip_pitch_link", "R_Hip"]
      - ["right_knee_link", "R_Knee"]
      - ["right_ankle_link", "R_Ankle"]
      - ["left_shoulder_roll_link", "L_Shoulder"]
      - ["left_elbow_link", "L_Elbow"]
      - ["left_hand_link", "L_Hand"]
      - ["right_shoulder_roll_link", "R_Shoulder"]
      - ["right_elbow_link", "R_Elbow"]
      - ["right_hand_link", "R_Hand"]
      - ["head_link", "Head"]


    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"
      - L_Elbow: "[0, -np.pi/2, 0]"
      - R_Elbow: "[0, np.pi/2, 0]"

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0.929, 0.867, 0.437] # pelvis
      - [0.929, 0.867, 0.437] # left_hip_yaw_joint
      - [0.929, 0.867, 0.437] # left_hip_roll_joint
      - [0.929, 0.867, 0.437] # left_hip_pitch_joint
      - [0.929, 0.867, 0.437] # left_knee_joint
      - [0.929, 0.867, 0.437] # left_ankle_joint
      - [0.929, 0.867, 0.437] # right_hip_yaw_joint
      - [0.929, 0.867, 0.437] # right_hip_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_pitch_joint
      - [0.929, 0.867, 0.437] # right_knee_joint
      - [0.929, 0.867, 0.437] # right_ankle_joint
      - [0.929, 0.867, 0.437] # torso_joint (waist_yaw_link)
      - [0.929, 0.867, 0.437] # left_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # left_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # left_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # left_elbow_joint
      - [0.929, 0.867, 0.437] # right_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # right_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # right_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0, 0.351, 0.613] # left_elbow_joint_extend
      - [0, 0.351, 0.613] # right_elbow_joint_extend
      - [0, 0.351, 0.613] # head_link

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1

